# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1

# Add your elasticsearch plugins setup here
RUN elasticsearch-plugin install ingest-attachment
